runtime: python
env: flex
entrypoint: gunicorn -b :$PORT Twillio:app

runtime_config:
  python_version: 3

# [START gae_flex_twilio_env]
env_variables:
    TWILIO_ACCOUNT_SID: ACce3d35b11990b0a5f86d17795ae7ffe6
    TWILIO_AUTH_TOKEN: 33808ddf18ac53ba89ffff98fbf2c460
    TWILIO_NUMBER: 19525294321
# [END gae_flex_twilio_env]